# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f43b73945a2e0f227e844ead38de1a19be28816e196d5bd2d2b96fb606ca6618af3609de70a2bb9f5fa1ac9c9c8cdbe73115372ec8869cbd9dc7d0c4e600944

test:
  secret_key_base: cc1638512433aaa5dee6703bffc97b2fd99b620f76844f981b5a4941688d0e308750ec2ecd363e4fb0610de02d1e4342a08179c16ba513e17e5f81642cea9a28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
